### ISSUE TITLE
Not working in Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by poon64** [mmtrt/notepad-plus-plus-snap#40]
Not working in Ubuntu 24.04
After installing it and starting it, it never completely runs, but it makes everything lock up untill I kills it. 
I have removed it and installed it a couple of times with the same result. 
I can't do anything else after I started it, everything is very slow, so I have to go to the terminal to kill it to get back the control of the sytem. I have left it running for hours to see if that makes any difference, but it's not working. I was not any problem with Ubuntu 22.04, bit it's not working with 24.04. 
I have a completely fresh installation of Ubuntu 24.04 and I tried to install it from the app center and also with snap from the terminal.

**Comment by mmtrt** [comment]
Had the same issue on 24.04, fix for this issue actually is downgrading the kernel to 6.7.x not sure why kernel 6.8.x creating this issue on noble with wine snaps though the same kernel version doesn't have any issues on jammy.

I had xanmod kernel though also the stock kernel so both had the same issues.

**Comment by poon64** [comment]
I uninstalled the Notepad++ that I had problems with and then I installed wine with apt "sudo apt install wine" 
I downloaded the latest Notepad++, then I installed Notepad++ trough wine "wine npp.8.6.5.Installer.x64.exe" 
This way of installing was working, no problems at all. the version of Notepadd++ is the same as the one causing problems.

**Comment by psebastian21** [comment]
I see this when trying to run it from the terminal:
`paulog@paulo-81y4:~$ notepad-plus-plus
Initialising Wine..
Gtk-Message: 17:47:53.415: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 17:47:53.415: Failed to load module "colorreload-gtk-module"
Installing application..
Running hook '/snap/notepad-plus-plus/403/sommelier/hooks/pre-install'
Starting application..
wine: failed to open "/home/paulog/snap/notepad-plus-plus/403/notepad-plus-plus/notepad-plus-plus.exe": c0000135
`

**Comment by mmtrt** [comment]
@psebastian21 that is related to #41 which is fixed already.

@poon64 can not reproduce that issue on `24.04` fresh install.

**Comment by lindolsang** [comment]
Hello @mmtrt 
First of all, thank you for your working. :)

By the way,
I have same issue.
But i have found something weired.
Could you check this point?

I am using Ubuntu 22.04 LTS with Xorg. (not wayland)
and the kernel was updated to 6.8.0 from 6.5.0
then
notepad-plus-plus was executing extremly slow

at that time,
I saw the Xorg is taking high CPU useage (it was about 100% til showing notepad-plus-plus UI)

Ubuntu

```
$ lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 22.04.4 LTS
Release: 22.04
Codename: jammy
```

Kernel
```
$ uname -r
6.8.0-40-generic
```

CPU useage after executing notepad-plus-plus
```
$ top
PID USER PR NI VIRT RES SHR S %CPU %MEM TIME+COMMAND
4989 juyeon 20 0 26.5g 138768 98692 R 99.3 0.4 0:22.44 Xorg
5177 juyeon 10 0 6402676 690324 157524 S 9.0 2.1 0:18.16 gnome-s+
440 root 19 -1 175396 69632 68608 S 0.7 0.2 0:00.66 systemd+
1137 syslog 20 0 222456 6016 4480 S 0.3 0.0 0:00.17 rsyslogd
```

if we can run gnome-shell on wayland instead of Xorg
this issue is not happened.

so i think the replication path is this.

```
Ubuntu 22.04
Kernel 6.8.0
gnome-shell is running with Xorg
Install notepad-plus-plus using snap (software center)
and then execute notepad-plus-plus
```

Could you check this? and share me how to fix this? :)

Thank you

**Comment by baruchsheffi** [comment]
Same issue here, just locks down.
My ubuntu 24.04 is a fresh install:
```shell
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
``` 
```shell
uname -r
6.8.0-41-generic
```

Before I threw my computer through the window ;), I saw the the process XORG using 100% of the CPU.

**Comment by mmtrt** [comment]
Pushed snap update today, can someone test if issue still happens.

**Comment by lindolsang** [comment]
Hello @mmtrt 
This is juyeon

I have tested today again.
It worked fine for me. 👍 

```
Notepad++ v8.6.9 (64 bit)

Snap store(Snap)
URL : snapcraft.io
Channel : latest / stable
Version : 8.6.9
```

Install step

```
Ubuntu software center -> search 'Notepad++' -> Install
```

Thank you! :)
