### ISSUE TITLE
Some characters on the interface cannot be displayed correctly

### ISSUE THREAD

**Issue by zhfreal** [mmtrt/notepad-plus-plus-snap#42]
There are some chars cannot show correctly. The top-right corner and the item in settings-localization.  It may be all about characterset?
![Screenshot from 2024-09-06 13-06-51-111111111111111111](https://github.com/user-attachments/assets/81d53fd7-41f9-4576-9dbe-ac3d12c85723)

**Comment by mmtrt** [comment]
localization missing are probably due to missing language specific fonts and UI missing symbol needs `Segoe UI` font which I can't add due to legal reason though it can be installed by user.

**Comment by zhfreal** [comment]
> localization missing are probably due to missing language specific fonts and UI missing symbol needs `Segoe UI` font which I can't add due to legal reason though it can be installed by user.

Thank you for the reply. I'm new to wine-snap applications. And I install "Segoe UI" fonts in my user's folder and make soft linker  into `~/snap/notepad-plus-plus/common/.wine/drive_c/windows/Fonts` for all of them. Then I restart npp, but no changes. Did I miss something?

**Comment by mmtrt** [comment]
yeah it doesn't work not sure which font responsible for symbols.

I fixed it with copying all windows fonts to `~/.fonts` then regenerated font cache with this command `fc-cache -v` and remove snap data `~/snap/notepad-plus-plus` to take effect.

**Comment by zhfreal** [comment]
> yeah it doesn't work not sure which font responsible for symbols.
> 
> I fixed it with copying all windows fonts to `~/.fonts` then regenerated font cache with this command `fc-cache -v` and remove snap data `~/snap/notepad-plus-plus` to take effect.

You saved my life!
